title: Zhang Jingru | Ruby 🪄
description: >-
  A space for my research, thoughts, and curiosities.
url: "https://ZhangJingru-Ruby.github.io"
baseurl: ""

# Author Info
author: Zhang Jingru
email: rubyrubber2001824@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Theme Settings
sass:
  sass_dir: _sass
  style: compressed

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Extras (optional but lovely)
social:
  github: https://github.com/ZhangJingru-Ruby
  email: rubyrubber2001824@gmail.com

# Optional integrations
disqus-identifier: your-disqus-shortname
google-analytics: UA-XXXXXXXXX-X
instafeed: false
