#-------------------------------
# General Site Settings
title: Ruby
logo: logo.svg # You can add own logo.
description: A personal academic site documenting my research progress, ideas, and inspirations.


#-------------------------------
# Author Settings
author:
  name: Jingru Zhang 
  image: 01.jpg
  say-hello: Hello, I'm <strong>Jingru Zhang</strong>, you can call me Ruby.
  bio:  I'm an aspiring researcher in robotics and artificial intelligence,
        with a passion for intelligent navigation, reinforcement learning, and autonomy systems.
        Currently pursuing my academic goals with curiosity and a drive to explore dynamic environments — both in research and in life.


#-------------------------------
# Contact links
linkedin: http://linkedin.com/in/景茹-张-146665357
email: rubyrubber2001824@gmail.com
edu-email: 202421100204@std.uestc.edu.cn
twitter: 
facebook: 
dribbble: 
instagram:
pinterest: 


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
